import { type Schema, Validator } from '@cfworker/json-schema'

/**
 * A JSON Schema (draft 2020-12) for a scenario's options. Typed loosely, so
 * `as const` schemas and ones generated by other libraries fit.
 */
export type OptionsSchema = { readonly [keyword: string]: unknown }

type Node = Record<string, unknown>

const isObject = (v: unknown): v is Node =>
  typeof v === 'object' && v !== null && !Array.isArray(v)

// Keywords that only say "something below failed"; the failure below says what.
const CASCADE = new Set([
  'properties',
  'patternProperties',
  'additionalProperties',
  'unevaluatedProperties',
  'items',
  'prefixItems',
  'unevaluatedItems',
  'allOf',
  'if',
  'then',
  'else',
  'dependentSchemas',
  '$ref',
  'false',
])

const path = (instanceLocation: string) =>
  instanceLocation === '#' ? 'options' : `options${instanceLocation.slice(1)}`

/**
 * Keys the schema doesn't name. An object schema that lists `properties`
 * rejects other keys unless it says otherwise (`additionalProperties` other
 * than false, or `patternProperties`), so a typo fails instead of vanishing.
 */
function unknownKeys(schema: unknown, value: unknown, at: string, out: string[]) {
  if (!isObject(schema)) return
  if (Array.isArray(value)) {
    if (isObject(schema.items))
      value.forEach((item, i) => unknownKeys(schema.items, item, `${at}/${i}`, out))
    return
  }
  if (!isObject(value) || !isObject(schema.properties)) return
  const props = schema.properties
  const open =
    (schema.additionalProperties !== undefined && schema.additionalProperties !== false) ||
    schema.patternProperties !== undefined ||
    // Composed schemas split their properties across branches; leave them to the validator.
    ['allOf', 'anyOf', 'oneOf', '$ref'].some((k) => schema[k] !== undefined)
  for (const [key, child] of Object.entries(value)) {
    if (key in props) unknownKeys(props[key], child, `${at}/${key}`, out)
    else if (!open)
      out.push(`${path(at)}: unknown option "${key}". Known: ${Object.keys(props).join(', ') || 'none'}`)
  }
}

const validators = new WeakMap<object, Validator>()

/**
 * Problems with `options` against `schema`, one line each, or [] when they
 * fit. No options are checked as `{}`, so required ones are reported.
 */
export function checkOptions(schema: OptionsSchema, options: unknown): string[] {
  let validator = validators.get(schema)
  if (!validator) {
    validator = new Validator(schema as Schema, '2020-12', false)
    validators.set(schema, validator)
  }
  const value = options === undefined ? {} : options
  const problems: string[] = []
  unknownKeys(schema, value, '#', problems)
  const result = validator.validate(value)
  if (!result.valid) {
    // Inside anyOf/oneOf, each branch's own failure is noise: the anyOf error says it.
    const leaves = result.errors.filter(
      (e) => !CASCADE.has(e.keyword) && !/\/(anyOf|oneOf)\/\d/.test(e.keywordLocation),
    )
    // Only cascades left: unknownKeys already named the key, or fall back to them all.
    const shown = leaves.length || problems.length ? leaves : result.errors
    for (const e of shown) problems.push(`${path(e.instanceLocation)}: ${e.error}`)
  }
  return [...new Set(problems)]
}
